import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRef, useState } from "react";


export default function Home() {

  const emailInputRef = useRef();
  const nameInputRef = useRef();
  const [prevMails, setPrevMails] = useState([]);

  const submitFormHandler = (event) => {
    event.preventDefault();
    const enteredEmail = emailInputRef.current.value;
    const enteredName = nameInputRef.current.value;

    // {email: 'eldorado@op.pl', text: 'You make good job'}
    fetch("/api/mails", {
      method: "POST", // or 'PUT'
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email: enteredEmail, name: enteredName }),
    })
      .then((response) => response.json())
      .then((data) => {
        console.log("Success from index:", data);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };

  const loadPrevMailsHandler = () => {
    fetch("/api/feedback")
      .then((response) => response.json())
      .then((data) => {
        setAllFeedback(data.feedback);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
    }


  return (
    <>
      <Head>
        <title>Motivation Booster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>The Home Page</h1>
      <form onSubmit={submitFormHandler}>
        <div>
          <label htmlFor="email">Your email address</label>
          <input type="email" id="email" ref={emailInputRef} />
        </div>
        <div>
          <label htmlFor="name">Your Name</label>
          <input id="name" rows="5" ref={nameInputRef}></input>
        </div>
        <button>Sing Me In</button>
      </form>
      
      <button onClick={loadPrevMailsHandler}>Load all feedback</button>
      <ul>
        {prevMails.map((mail) => (
          <li key={mail.id}>
            { mail.body }
          </li>
        ))}
      </ul>

      </main>
    </>
  )
}
