import Head from 'next/head'

import { useRef, useState } from "react";


export default function Home() {

  const emailInputRef = useRef();
  const nameInputRef = useRef();
  const [prevMails, setPrevMails] = useState([]);

  const submitFormHandler = (event) => {
    event.preventDefault();
    const enteredEmail = emailInputRef.current.value;
    const enteredName = nameInputRef.current.value;

    
    fetch("/api/users", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email: enteredEmail, name: enteredName }),
    })
      .then((response) => response.json())
      .then((data) => {
        console.log("Success from index:", data);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };

  const loadPrevMailsHandler = () => {
    fetch("/api/mails")
      .then((response) => response.json())
      .then((data) => {
        setPrevMails(data.mails);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
      console.log(prevMails);
    }


  return (
    <>
      <Head>
        <title>Motivation Booster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1>Motivate Yourself with Motivation Booster!</h1>
      <form onSubmit={submitFormHandler} className='newsletter'>
        <div>
          <label htmlFor="email">Your email address</label>
          <input type="email" id="email" ref={emailInputRef} />
        </div>
        <div>
          <label htmlFor="name">Your Name</label>
          <input id="name" rows="5" ref={nameInputRef}></input>
        </div>
        <button className='button'>Sing Me In</button>
      </form>
      
      <button className='button' onClick={loadPrevMailsHandler}>Load all feedback</button>
  
        {prevMails.map((mail) => (
          
            <div className='email'>
              <h2>
              { mail.subject }
              </h2>
            
            <text>{ mail.body }</text>
            </div>
            
        ))}
    

      </main>
    </>
  )
}
